export const ART_STYLES: string[] = [
    "stencil",
    "ballpoint pen art",
    "pencil sketch",
    "political cartoon from a U.S. newspaper",
    "coloring-in sheet",
    "children's drawing",
    "watercolor",
    "colored pencil drawing",
    "oil painting",
    "pastel painting",
    "airbrush",
    "collage",
    "vector art",
    "low poly",
    "layered paper",
    "sticker illustration",
    "storybook",
    "digital painting",
    "botanical illustration",
    "Voroni diagram",
    "3D render",
    "Scratch art",
    "Comic book art",
    "Anime",
    "Pixar",
    "Studio Ghibli",
    "disney",
    "pixel art",
    "cave paintings",
    "Ancient Egypt papyrus",
    "renaissance painting",
    "rococo painting",
    "impressionist painting",
    "post-impressionism painting",
    "cubism painting",
    "abstract expressionism painting",
    "pop art",
    "fauvism painting",
    "surrealist painting",
    "pointillism"
];